public class TipoSimbolo {
    public static final int ERROR = -1;
    public static final int IDENTIFICADOR = 0;
    public static final int OPADIC = 5;
    public static final int OPMULT = 6;
    public static final int PESOS = 23;
    public static final int E = 47;
    public static final int ENTERO= 1;
    public static final int REAL= 2;
    public static final int OPRELAC= 7;
    public static final int OPOR= 8;
    public static final int OPAND= 9;
    public static final int OPNOT= 10;
    public static final int OPIGUALDAD= 11;
    public static final int PUNTOYCOMA= 12;
    public static final int COMA= 13;
    public static final int PARENABI= 14;//parentesis abierto "("
    public static final int PARENCER= 15;//parentesis cerrado ")"
    public static final int CORCHETEABI= 16;//corchete abierto "{"
    public static final int CORCHETECER= 17;//corchete cerrado "}"
    public static final int IGUAL= 18;
    public static final int IF= 19;
    public static final int WHILE= 20;
    public static final int RETURN= 21;
    public static final int ELSE= 22;
    public static final int CADENA= 3;
    public static final int TIPO= 4;
    public static final int ESPACIO= 46;
    public static final int PROGRAMA= 24;
    public static final int DEFINICIONES= 25;
    public static final int DEFINICION= 26;
    public static final int DEFVAR= 27;
    public static final int LISTAVAR= 28;
    public static final int DEFFUNC= 29;
    public static final int PARAMETROS= 30;
    public static final int LISTAPARAM= 31;
    public static final int BLOQFUNC= 32;
    public static final int DEFLOCALES= 33;
    public static final int DEFLOCAL= 34;
    public static final int SENTENCIAS= 35;
    public static final int SENTENCIA= 36;
    public static final int OTRO= 37;
    public static final int BLOQUE= 38;
    public static final int VALORREGRESA = 39;
    public static final int ARGUMENTOS = 40;
    public static final int LISTAARGUMENTOS = 41;
    public static final int TERMINO= 42;
    public static final int LLAMADAFUNC= 43;
    public static final int SENTENCIABLOQUE= 44;
    public static final int EXPRESION = 45;
}
